project:
  type: website

website:
  title: "Zac Davies Blog"
  site-url: "https://zacdav-db.github.io/blog/"
  description: "Posts on R, Arrow, Databricks, data engineering, and AI."
  navbar:
    title: "zac davies"
    left:
      - text: Blog
        href: index.qmd
      - text: Talks
        href: https://github.com/zacdav-db/presentations
    right:
      - icon: github
        href: https://github.com/zacdav-db
      - icon: linkedin
        href: https://www.linkedin.com/in/zacdav/
format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
